### ISSUE TITLE
Webpack & PostCSS 6 Support

### ISSUE THREAD

**Issue by oleksiibilous** [arccoza/postcss-if-media#5]
Hi

Looks like `postcss-if-media` behaves awkward with `postcss 6`

Input:
```
.test {
  margin: 0 1rem;
  margin: 0 3rem ?if media (min-width: 900px);
}
```

PostCSS 5 Output:
```
.test {
  margin: 0 1rem;
}

@media (min-width: 900px) {
  .test {
     margin: 0 3rem;
  }
}
```

PostCSS 6 Output:
```
.test {
  margin: 0 1rem;
}

@media (min-width: 900px) {
  .test {}
}
```

Can you advise, please?🙂

**Comment by arccoza** [comment]
Hmm, I will have a look.

**Comment by arccoza** [comment]
After testing `postcss-if-media` against your example with PostCSS@6.0.0 and PostCSS@6.0.1 I couldn't reproduce your error. Could you share more info about your build, or maybe just a link to your repo?

**Comment by oleksiibilous** [comment]
hmm...maybe the problem is caused by another plugin. Here is my list of plugins:

```
  postcssImport({ path: context }),
  postcssConditionals(),
  postcssEach(),
  postcssFor(),
  postcssIfMedia(),
  postcssNested(),
  postcssNext(),
  postcssRucksack({
    alias: false,
    inputPseudo: false,
    shorthandPosition: false,
  }),
  postcssShort(),
  postcssLost(),
  postcssMQPacker(),
  postcssBrandColors(),
  postcssGradientTransparencyFix(),
  postcssDoIUse({ ignore: ['flexbox'] }),
  postcssReporter({ clearReportedMessages: true }),
```

```
    "lost": "8",
    "portfinder": "1",
    "postcss-brand-colors": "1",
    "postcss-conditionals": "2",
    "postcss-cssnext": "2",
    "postcss-each": "0.10",
    "postcss-for": "2",
    "postcss-gradient-transparency-fix": "2",
    "postcss-if-media": "1",
    "postcss-import": "10",
    "postcss-loader": "2",
    "postcss-nested": "2",
    "postcss-reporter": "3",
    "postcss-short": "4",
    "rucksack-css": "0.9",
```

I'm using `postCSS` with `webpack` & `cssmodules`

I think I will be able to create demo repo for you later this week

Thanks

**Comment by oleksiibilous** [comment]
I've created a simple demo. [Check it out](https://github.com/oleksiibilous/example-posts-if-media-issue-5). Run `yarn build` after cloning. It should show `'foo' if width < 900px` and `'bar' if width  > 900`. You can check compiled CSS inside `<head><style>...</style></head>`

Let me know if it helps

**Comment by arccoza** [comment]
I believe I've found a fix, although I'm not 100% sure who is at fault; either webpack or postcss-loader.
Test the latest commit with your code, if everything is rosy, I'll publish an update to npm.

**Comment by oleksiibilous** [comment]
Now it works. I've pushed an update to my example, so you can check it too if you want. Thanks for your help👍

**Comment by arccoza** [comment]
No problem; v1.0.3 with fix published to NPM.
